- name: CentOS Basic Environment
  hosts: all
  tasks:
    - name: Extra Packages for Enterprise Linux
      yum: pkg=epel-release
    - name: Installs Envirement Packages
      yum: pkg={{ item }}
      with_items:
        - mc
        - htop
        - screen
        - net-tools
